### ISSUE TITLE
[BUG] - Removing root thunar

### ISSUE THREAD

**Issue by VinayChaurasiyaA** [tcet-opensource/tcet-linux#109]
### Describe the bug

- While running terminal through thunar as root, we used to get bug in that terminal

### How to Reproduce?

1. Open thunar
2. Now open it as root
3. open terminal as being in root -> thunar

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by dipeshsingh253** [comment]
Hey @VinayChaurasiyaA , I would like to work on this issue. Though I am good with Linux stuff this is my first time contributing to an actual distro so I am excited for this.

**Comment by harshau007** [comment]
> Hey @VinayChaurasiyaA , I would like to work on this issue. Though I am good with Linux stuff this is my first time contributing to an actual distro so I am excited for this.

Hey @dipeshsingh253 , this issue has been resolved but we would encourage you to look into other open issues in our organization

**Comment by VinayChaurasiyaA** [comment]
hey @dipeshsingh253 , we would love to see your contribution but as of now this issue is been resolved. Appreciate if you look into other issues and work towards it!

**Comment by Akash6222** [comment]
@dipeshsingh253 I like your dedication to work on TCET Linux , I'm glad to see you took your first step in contribution to open source.
Feel free to join our discord server https://discord.com/invite/r7ZhAREg2M for future updates
