### ISSUE TITLE
[UPDATE] Readme 

### ISSUE THREAD

**Issue by Akash6222** [tcet-opensource/tcet-linux#63]
Update the Readme of Repo and make sure to include following things:

TCET Linux :-
- [x] What is TCET-Linux
- [x] About TCET-Linux

Welcome app :-
- [x] Define welcome app
- [x] Add some images
- [x] Define welcome functions in bullet points
 
Terminal :-
- [x] Define Autosuggestion
- [x] Define Autocomplete
- [x] Install and remove package
- [x] Neofetch image

Requirements :-
- [x] What are requirements for installing TCET-Linux

About :-
- [x] #83
- [x] Website Link

Explain above all points and add image wherever needed

**Comment by driti29** [comment]
TCET Linux, the ultimate choice for enthusiasts and professionals alike, has received exciting updates to enhance your computing experience. With the addition of Starship and an optimized terminal, your command-line interactions are now smoother and more efficient than ever. Say hello to the future with the newly integrated Welcome app, which guides you through setup and familiarizes you with TCET Linux's key features. Want to flaunt your system's prowess? Neofetch has been seamlessly integrated to display vital system information in style. From its lightning-fast performance to its robust security measures, TCET Linux continues to shine. Stay connected and informed by visiting the TCET Linux Website and accessing our comprehensive Docs website. Discover a new era of computing with TCET Linux – where power, usability, and community converge seamlessly.

**Comment by Rishabh672003** [comment]
gpt generated?

**Comment by driti29** [comment]
> gpt generated?

some of them

**Comment by Akash6222** [comment]
There are some things that I have to change in issue 
Give me a minute

**Comment by Akash6222** [comment]
For current time i have updated the task..
This maybe be change in future... @driti29 @gayatrirane04 @Bhumi1685

**Comment by beans9926** [comment]
I suggest removing "How TCET-linux will help you in day-to-day life" point as it is not needed
