### ISSUE TITLE
[FEATURE] Auto tile

### ISSUE THREAD

**Issue by Akash6222** [tcet-opensource/tcet-linux#65]
- [x] Added auto tile window
- [x] Window should be divided into 4 parts

**Comment by Rishabh672003** [comment]
so in this are we trying to emulate tiling that happens on window managers here?
i think that will take a lot of hacks but still let me see what i can come up with
@Akash6222

**Comment by Akash6222** [comment]
No
Currently when we launch any application, all application opens at middle of screen which makes inconvientent to use previous one.
We have to add tile feature which will align it first left top then right top then left botton and then right bottom.

**Comment by Akash6222** [comment]
> so in this are we trying to emulate tiling that happens on window managers here? i think that will take a lot of hacks but still let me see what i can come up with @Akash6222

No
Currently when we launch any application, all application opens at middle of screen which makes inconvientent to use previous one.
We have to add tile feature which will align it first left top then right top then left botton and then right bottom.

**Comment by Akash6222** [comment]
Do you have something else in mind ?
